### ISSUE TITLE
thrift语法不兼容,当include 语句出现在第一行,会出现如下错误

### ISSUE THREAD

**Issue by wangtingwei** [dapeng-soa/dapeng-soa#1]
```java
/xm-project-api/src/main/resources/thrifts/project_domain.thrift success
java.io.FileNotFoundException: project_domain.scala.thrift
	at com.twitter.scrooge.frontend.ThriftParser.$anonfun$parseFileUncached$1(ThriftParser.scala:455)
	at scala.Option.getOrElse(Option.scala:121)
	at com.twitter.scrooge.frontend.ThriftParser.parseFileUncached(ThriftParser.scala:455)
	at com.twitter.scrooge.frontend.ThriftParser.parseFile(ThriftParser.scala:449)
	at com.twitter.scrooge.frontend.ThriftParser.$anonfun$include$5(ThriftParser.scala:398)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:137)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$map$1(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
Error: project_domain.scala.thrift
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.180 s
	at scala.util.parsing.combinator.Parsers.$anonfun$positioned$1(Parsers.scala:865)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.RegexParsers$$anon$3.apply(RegexParsers.scala:135)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$map$1(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Success.flatMapWithNext(Parsers.scala:143)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$flatMap$1(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$append$1(Parsers.scala:249)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$append$1(Parsers.scala:249)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers.$anonfun$rep1$1(Parsers.scala:727)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$append$1(Parsers.scala:249)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$flatMap$1(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$flatMap$1(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$map$1(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$flatMap$1(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$$anon$2.$anonfun$apply$2(Parsers.scala:882)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.util.parsing.combinator.Parsers$$anon$2.apply(Parsers.scala:882)
	at scala.util.parsing.combinator.RegexParsers.parse(RegexParsers.scala:160)
	at scala.util.parsing.combinator.RegexParsers.parse$(RegexParsers.scala:159)
	at com.twitter.scrooge.frontend.ThriftParser.parse(ThriftParser.scala:26)
	at scala.util.parsing.combinator.RegexParsers.parseAll(RegexParsers.scala:176)
	at scala.util.parsing.combinator.RegexParsers.parseAll$(RegexParsers.scala:175)
	at com.twitter.scrooge.frontend.ThriftParser.parseAll(ThriftParser.scala:26)
	at com.twitter.scrooge.frontend.ThriftParser.parse(ThriftParser.scala:438)
	at com.github.dapeng.code.parser.ThriftCodeParser.generateDoc(ThriftCodeParser.scala:89)
	at com.github.dapeng.code.parser.ThriftCodeParser.$anonfun$toServices$1(ThriftCodeParser.scala:454)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at com.github.dapeng.code.parser.ThriftCodeParser.toServices(ThriftCodeParser.scala:453)
	at com.github.dapeng.code.Scrooge$.main(Scrooge.scala:141)
	at com.github.dapeng.code.Scrooge.main(Scrooge.scala)
	at com.github.dapeng.maven.plugin.GenerateFilePlugin.execute(GenerateFilePlugin.java:58)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:46)
```

**Comment by jackliang18588733858** [comment]
非常感谢指出该bug，我们已经在master针对该问题做了兼容。
```java
//如果是scala，需要重写namespace
    val finalTxt = if (language.equals("scala")) {
      // getNamespaceLine => "namespace java xxxxxx.xx.xx"
      // 获取namespace
      val namespaceLine = Source.fromFile(resource).getLines().find(_.trim.startsWith("namespace"))
      namespaceLine match {
        case Some(i) =>
          val namespace = i.split(" ").reverse.head
          val scalaNamespace = toScalaNamespace(namespace)
          txt.replace(namespace,scalaNamespace)
        case None =>
          println("[Warning] you should specific your namespace statement at head of your thrift file. like: namespace java YourPackageName")
          txt
      }
    } else txt
```
